Models/Category.cs
namespace la_mia_pizzeria_static.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Pizza>? Pizzas { get; set; }
        public Category()
        {

        }

        public Category(int id, string name)
        {
            Id = id;
            Name = name;
        }
    }

    
}

Controllers/CategoryController.cs
using la_mia_pizzeria_static.Data;
using la_mia_pizzeria_static.Models;
using la_mia_pizzeria_static.Models.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace la_mia_pizzeria_static.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private IDbCategoryRepository categoryRepository;

        public CategoryController()
        {
          categoryRepository = new ListCategoryRepository();
        }
        public IActionResult Index()
        {
            ViewData["Title"] = "Categorie";
            List<Category> categories = categoryRepository.Get();
            return View(categories);
        }

        public IActionResult Detail(int id)
        {
            ViewData["Title"] = "Categorie";
            Category category = categoryRepository.Get(id);
            if (category == null)
                return NotFound();
            return View(category);
        }
        public IActionResult Create()
        {
            ViewData["Title"] = "Crea Categoria";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            ViewData["Title"] = "Crea Categoria";
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            categoryRepository.Create(category);
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            if (!categoryRepository.Exists(id))
                return NotFound();
            return View(categoryRepository.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Category category)
        {
            category.Id = id;
            if (!ModelState.IsValid)
                return View(category);
            categoryRepository.Update(category);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            if (!categoryRepository.Exists(id))
                return NotFound();
            if (categoryRepository.HasConstraint(id))
            {
                return View("ImpossibleDelete");
            }
            categoryRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/PizzaController.cs
using la_mia_pizzeria_static.Data;
using la_mia_pizzeria_static.Models;
using la_mia_pizzeria_static.Models.Form;
using la_mia_pizzeria_static.Models.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.SqlServer.Server;
using System.Data;

namespace la_mia_pizzeria_static.Controllers
{
    [Authorize]
    public class PizzaController : Controller
    {
     
        private IDbPizzaRepository pizzaRepository;

        public PizzaController(IDbPizzaRepository _pizza)
        {
            pizzaRepository = _pizza;
        }
        public IActionResult Index()
        {
            ViewData["Title"] = "Todi Pizza";
            return View(pizzaRepository.Get());
        }
        // filtro per pizze con categoria
        public IActionResult CategoryFilter(int categoryId)
        {

            List<Pizza> Pizze = pizzaRepository.GetByCategoryId(categoryId);
            ViewData["Title"] = "Todi Pizza";
            return View("Index", Pizze);
        }

        public IActionResult Detail(int id)
        {
            Pizza pizza = pizzaRepository.Get(id);
            ViewData["Title"] = "Todi Pizza | " + pizza.Name;
            return View(pizza);
        }
        public IActionResult Create()
        {
            
            return View(pizzaRepository.CreateForm());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzaForm formData)
        {
            if (!ModelState.IsValid)
            {
                
                return View(pizzaRepository.CreateForm(formData));
            }

            pizzaRepository.Create(formData.Pizza, formData.SelectedIngredients);

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            if (!pizzaRepository.Exists(id))
                return NotFound();
           
            return View(pizzaRepository.CreateForm(id));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, PizzaForm formData)
        {
            formData.Pizza.Id = id;
            if (!ModelState.IsValid)
            {
                return View(pizzaRepository.CreateForm(formData));
            }

            pizzaRepository.Update(formData.Pizza, formData.SelectedIngredients);

            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Pizza pizza = pizzaRepository.Get(id);
            if (pizza == null)
            {
                return NotFound();
            }

            pizzaRepository.Delete(pizza);
            
            return RedirectToAction("Index");
        }
    }
}

Views/Category/Create.cshtml
@model Category

<div class="container">
    <div class="row justify-content-center">
        <div class="col col-md-8">
            <form asp-controller="Category" asp-action="Create" method="post">

                <div class="mb-3">
                    <strong>Titolo:</strong>
                    <input asp-for="Name" class="d-block w-100" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="text-end">
                    <input type="submit" class="btn btn-small btn-success" value="Salva">
                </div>
            </form>
        </div>
    </div>
</div>

Views/Category/Detail.cshtml
@model Category

<div class="container">
    <div class="text-center">
        <h3 class="display-4">Categorie</h3>
        <h5> <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Indietro</a></h5>
        <div class="py-5"></div>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">
                            <span class="badge bg-primary">@Model.Name</span>
                        </h2>
                        <div>
                            <a class="btn btn-small btn-primary" href="@Url.Action("Detail", new {id = Model.Id})" class="text-end">Dettagli</a>
                            <a class="btn btn-small btn-info" href="@Url.Action("Update", new {id = Model.Id})" class="text-end">Modifica</a>
                            <a class="btn btn-small btn-success" href="@Url.Action("CategoryFilter", "Pizza", new {id = Model.Id})" class="text-end">Vedi Pizze</a>
                            <form asp-controller="Category" asp-action="Delete" asp-route-id="@Model.Id" method="post" class="d-inline-block">
                                <input type="submit" class="btn btn-small btn-danger" value="Elimina">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Category/ImpossibleDelete.cshtml
@model Category

<div class="container">
    <div class="text-center">
        <h3 class="display-4">Errore</h3>
        <h5> <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Indietro</a></h5>
        <div class="py-5"></div>
        <div class="row row-cols-1 row-cols-md-3 g-4 justify-content-center">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">
                            Impossibile cancellare la categoria perchè viene usata da delle pizze
                        </h4>
                        <div>
                            <a class="btn btn-small btn-primary" asp-area="" asp-controller="Category" asp-action="Index">Indietro</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Category/Index.cshtml
@model List<Category>

<div class="container">
    <div class="text-center">
        <h3 class="display-4">Categorie</h3>
        <h5> <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Create">Aggiungi Categoria</a></h5>
        <div class="py-5"></div>

        @if (Model.Count() < 1)
        {
            <h4>Non ci sono categorie nel database</h4>
        }
        else
        {
            <div class="row row-cols-1 row-cols-md-3 g-4">
                @foreach (Category category in Model)
                {
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <h2 class="card-title">
                                    <span class="badge bg-primary">@category.Name</span>
                                </h2>
                                <div>
                                    <a class="btn btn-small btn-primary" href="@Url.Action("Detail", new {id = category.Id})" class="text-end">Dettagli</a>
                                    <a class="btn btn-small btn-info" href="@Url.Action("Update", new {id = category.Id})" class="text-end">Modifica</a>
                                    <a class="btn btn-small btn-success" href="@Url.Action("CategoryFilter", "Pizza", new {id = category.Id})" class="text-end">Vedi Pizze</a>
                                    <form asp-controller="Category" asp-action="Delete" asp-route-id="@category.Id" method="post" class="d-inline-block">
                                        <input type="submit" class="btn btn-small btn-danger" value="Elimina">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
</div>

Views/Category/Update.cshtml
@model Category

<div class="container">
    <div class="row justify-content-center">
        <div class="col col-md-8">
            <form asp-controller="Category" asp-action="Update" asp-route-id="@Model.Id" method="post">

                <div class="mb-3">
                    <strong>Titolo:</strong>
                    <input asp-for="Name" class="d-block w-100" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="text-end">
                    <input type="submit" class="btn btn-small btn-success" value="Salva">
                </div>
            </form>
        </div>
    </div>
</div>